#!/bin/bash
# Runs all unittests locally inside a Python virtual environment.
# Run a specific test by passing its name as a parameter.
# e.g. ./run_tests tests/test_trie.py::TestTrie::test_empty
set -e
if [ ! -d .env ]; then
    python3.11 -m venv .env
    . .env/bin/activate
    pip install pytest
else
    . .env/bin/activate
fi;
pytest "$@"
